/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.hotel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ItemFrom extends javax.swing.JFrame {

    /**
     * Creates new form ItemFrom
     */
    public ItemFrom() {
        initComponents();
    }
     private void clearFields(){
         txt_quantity.setText(null);
         txt_unitPrice.setText(null);
         tbl_item.setModel(new DefaultTableModel(null,new Object[]{"Item Name","Unit Price","Quantity","Sub Total"}));
         rb_totalPrice.setText(null);
         cb_selectItem.setSelectedItem("Select");  
         txt_cName.setText(null);
         txt_cPhone.setText(null);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rb_food = new javax.swing.JRadioButton();
        rb_drinks = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rb_remove = new javax.swing.JButton();
        cb_selectItem = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_item = new javax.swing.JTable();
        txt_quantity = new javax.swing.JTextField();
        rb_totalPrice = new javax.swing.JTextField();
        txt_unitPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        rb_add = new javax.swing.JButton();
        rb_change = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rb_save = new javax.swing.JButton();
        rb_dataBase = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_cName = new javax.swing.JTextField();
        txt_cPhone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        user_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Hotel Paradise Fast Food Shop");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        rb_food.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup1.add(rb_food);
        rb_food.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_food.setText("Fast Food");
        rb_food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_foodActionPerformed(evt);
            }
        });

        rb_drinks.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup1.add(rb_drinks);
        rb_drinks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_drinks.setText("Soft Drinks");
        rb_drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_drinksActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select Type:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(rb_food)
                .addGap(161, 161, 161)
                .addComponent(rb_drinks)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_food)
                    .addComponent(rb_drinks)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Unit Price:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Selected Item:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total Price:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Quantity:");

        rb_remove.setBackground(new java.awt.Color(255, 51, 0));
        rb_remove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_remove.setForeground(new java.awt.Color(255, 255, 255));
        rb_remove.setText("Remove");
        rb_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_removeActionPerformed(evt);
            }
        });

        cb_selectItem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        tbl_item.setBackground(new java.awt.Color(153, 153, 153));
        tbl_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Unit Price", "Quantity", "Sub Total"
            }
        ));
        tbl_item.setFocusable(false);
        tbl_item.setGridColor(new java.awt.Color(153, 153, 255));
        tbl_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_itemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_item);

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rb_add.setBackground(new java.awt.Color(255, 102, 102));
        rb_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_add.setText("Add");
        rb_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_addActionPerformed(evt);
            }
        });

        rb_change.setBackground(new java.awt.Color(255, 204, 51));
        rb_change.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_change.setText("Change");
        rb_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_changeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select Item:");

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));

        rb_save.setBackground(new java.awt.Color(255, 255, 255));
        rb_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_save.setText("Save");
        rb_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_saveActionPerformed(evt);
            }
        });

        rb_dataBase.setBackground(new java.awt.Color(255, 255, 255));
        rb_dataBase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_dataBase.setText("Back To Home");
        rb_dataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_dataBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(rb_save)
                .addGap(18, 18, 18)
                .addComponent(rb_dataBase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_save)
                    .addComponent(rb_dataBase))
                .addGap(24, 24, 24))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Customar Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Customar Phone No:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cName))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_cName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_cPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_unitPrice)
                            .addComponent(cb_selectItem, 0, 171, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(rb_add))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rb_change)
                                .addGap(18, 18, 18)
                                .addComponent(rb_remove))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_selectItem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_unitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_add)
                    .addComponent(rb_change)
                    .addComponent(rb_remove)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No", "Item Name", "Quantity", "Sub Total", "Date & Time"
            }
        ));
        user_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(user_table);

        jPanel4.setBackground(java.awt.Color.green);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Sell History");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_foodActionPerformed
        // TODO add your handling code here:
        txt_unitPrice.setText("0");
        txt_quantity.setText("0");
        cb_selectItem.removeAllItems();
        cb_selectItem.addItem("Select");
        cb_selectItem.addItem("Burger");
        cb_selectItem.addItem("Subway");
        cb_selectItem.addItem("CHICKEN SANDWICH");
        cb_selectItem.addItem("CURLY FRIES");
    }//GEN-LAST:event_rb_foodActionPerformed

    private void rb_drinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_drinksActionPerformed
        // TODO add your handling code here:
         txt_unitPrice.setText("0");
        txt_quantity.setText("0");
        cb_selectItem.removeAllItems();
        cb_selectItem.addItem("Select");
        cb_selectItem.addItem("Coca-Cola");
        cb_selectItem.addItem("Pepsi");
        cb_selectItem.addItem("Sprite");
        cb_selectItem.addItem("Mountain Dew");
    }//GEN-LAST:event_rb_drinksActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                String item=cb_selectItem.getSelectedItem().toString();
        if(item.equalsIgnoreCase("Burger")){
            txt_unitPrice.setText("250");
            txt_quantity.setText("1");
        }else if(item.equalsIgnoreCase("Subway")){
            txt_unitPrice.setText("150");
            txt_quantity.setText("1");
        }else if(item.equalsIgnoreCase("CHICKEN SANDWICH")){
            txt_unitPrice.setText("190");
            txt_quantity.setText("1");
        }else if(item.equalsIgnoreCase("CURLY FRIES")){
            txt_unitPrice.setText("80");
            txt_quantity.setText("1");
        }else if(item.equalsIgnoreCase("Coca-Cola")){
            txt_unitPrice.setText("120");
            txt_quantity.setText("1");
        }else if(item.equalsIgnoreCase("Pepsi")){
            txt_unitPrice.setText("90");
            txt_quantity.setText("1");
        }else if(item.equalsIgnoreCase("Sprite")){
            txt_unitPrice.setText("100");
            txt_quantity.setText("1");
        }else if(item.equalsIgnoreCase("Mountain Dew")){
            txt_unitPrice.setText("110");
            txt_quantity.setText("1");
        }else{
            txt_unitPrice.setText("0");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rb_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_addActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_item.getModel();
        int subTotal=Integer.parseInt(txt_unitPrice.getText())*Integer.parseInt(txt_quantity.getText());
        model.addRow(new Object[]{cb_selectItem.getSelectedItem().toString(),txt_unitPrice.getText(),txt_quantity.getText(),String.valueOf(subTotal)});
        int total=0;
        for(int i=0;i<tbl_item.getRowCount();i++){
            total=total+Integer.parseInt(model.getValueAt(i, 3).toString());            
        }
        rb_totalPrice.setText(String.valueOf(total));
    }//GEN-LAST:event_rb_addActionPerformed

    private void rb_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_changeActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tbl_item.getModel();
        int subTotal=Integer.parseInt(txt_unitPrice.getText())*Integer.parseInt(txt_quantity.getText());
        model.setValueAt(cb_selectItem.getSelectedItem().toString(),tbl_item.getSelectedRow(),0);
        model.setValueAt(txt_unitPrice.getText(),tbl_item.getSelectedRow(),1);
        model.setValueAt(txt_quantity.getText(),tbl_item.getSelectedRow(),2);
        model.setValueAt(String.valueOf(subTotal),tbl_item.getSelectedRow(),3);
        int total=0;
        for(int i=0;i<tbl_item.getRowCount();i++){
            total=total+Integer.parseInt(model.getValueAt(i, 3).toString());            
        }
            rb_totalPrice.setText(String.valueOf(total));
    }//GEN-LAST:event_rb_changeActionPerformed

    private void rb_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_removeActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tbl_item.getModel();
        model.removeRow(tbl_item.getSelectedRow());
        int total=0;
        for(int i=0;i<tbl_item.getRowCount();i++){
            total=total+Integer.parseInt(model.getValueAt(i, 3).toString());            
        }
        rb_totalPrice.setText(String.valueOf(total));
    }//GEN-LAST:event_rb_removeActionPerformed

    private void rb_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_saveActionPerformed
        // TODO add your handling code here:
         try{
            DefaultTableModel model = (DefaultTableModel) tbl_item.getModel();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/myhotel_db","root","");
            String query ="Insert into data_item (item_name,quantity,sub_total) values (?,?,?)"; 
            JOptionPane.showMessageDialog(rootPane, "Database Connected");
             
            for(int i=0;i<tbl_item.getRowCount();i++){
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, model.getValueAt(i, 0).toString());
                ps.setInt(2, Integer.parseInt(model.getValueAt(i, 1).toString()));
                ps.setInt(3, Integer.parseInt(model.getValueAt(i, 2).toString()));
                ps.execute();
            }
            PreparedStatement ps = con.prepareStatement(query);
            // ps.setString(4, txt_cName.getText());
             //ps.setString(5, txt_cPhone.getText());
            ps.execute();
            
        }catch(Exception e){
               JOptionPane.showMessageDialog(rootPane, e);
            
        }          
         user_table.setModel(new DefaultTableModel(null,new Object[]{"Serial No","Item Name","Quantity","Sub Total","Date & Time"}));
                         try{
            DefaultTableModel model = (DefaultTableModel) user_table.getModel();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/myhotel_db","root","");
            String query ="Select * from data_item"; 
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery(query);
            
            while(r.next()){
                model.addRow(new Object[] {
                    //r.getString(query)
                r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                r.getString(5),
                });
            }
       
            
        }catch(Exception e){

        }
         //
            clearFields();
    }//GEN-LAST:event_rb_saveActionPerformed

    private void tbl_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_itemMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_item.getModel();
        cb_selectItem.setSelectedItem(model.getValueAt(tbl_item.getSelectedRow(), 0));
        txt_unitPrice.setText(model.getValueAt(tbl_item.getSelectedRow(), 1).toString());
        txt_quantity.setText(model.getValueAt(tbl_item.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tbl_itemMouseClicked

    private void rb_dataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_dataBaseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HotelHome dh=new HotelHome();
        dh.setVisible(true);
    }//GEN-LAST:event_rb_dataBaseActionPerformed

    private void user_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tableMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_user_tableMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_selectItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rb_add;
    private javax.swing.JButton rb_change;
    private javax.swing.JButton rb_dataBase;
    private javax.swing.JRadioButton rb_drinks;
    private javax.swing.JRadioButton rb_food;
    private javax.swing.JButton rb_remove;
    private javax.swing.JButton rb_save;
    private javax.swing.JTextField rb_totalPrice;
    private javax.swing.JTable tbl_item;
    private javax.swing.JTextField txt_cName;
    private javax.swing.JTextField txt_cPhone;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_unitPrice;
    private javax.swing.JTable user_table;
    // End of variables declaration//GEN-END:variables
}
